# //
# // Functional links
# //
title: "S"
# //
# // Outputting
# // 
timezone: Europe/London
permalink: pretty
liquid:
  error_mode: warn
  strict_filters: true
  strict_variables: false
# //
# // Where things are
# //
source: ./jekyll/
destination: ./_site/
plugins:
  - jekyll-archives
# //
# // Serving
# //
host: 0.0.0.0
port: 6767
markdown: kramdown

keep_files: [ "assets", "js", "video" ]

include: [ _headers, humans.txt, robots.txt, sitemap.xml ]

collections_dir: collections

collections:
  posts:
    output: true

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/archive/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/topics/:name/'
    category: '/categories/:name/'

defaults:
  - scope:
      type: "posts"
    values:
      permalink: /:categories/:title/
      layout: "post"
      author: "Shannon Young"
      post: true

repository: "https://github.com/mrshannonyoung/2020/"