# //
# // Functional links
# //
title: "Shannon Young"
email: "&#109;&#97;i&#108;&#116;&#111;&#58;%6De&#64;%7&#51;h%&#54;1n&#110;%6F&#110;%79%&#54;F&#37;75%6E%&#54;&#55;&#46;co&#46;uk"
# //
# // Outputting
# // 
timezone: Europe/London
permalink: pretty
liquid:
  error_mode: warn
  strict_filters: true
  strict_variables: false
# //
# // Where things are
# //
source: ./jekyll/
destination: ./_site/
plugins:
  - jekyll-archives
# //
# // Serving
# //
host: 0.0.0.0
port: 6767
markdown: kramdown

kramdown:
  parse_block_html: true

keep_files: [ "assets", "js", "video" ]

include: [ _headers, humans.txt, robots.txt ]

collections_dir: collections

collections:
  posts:
    output: true

jekyll-archives:
  enabled:
    - year
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/archive/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/topics/:name/'
    category: '/categories/:name/'

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      permalink: /:categories/:title/
      layout: "post"
      author: "Shannon Young"
      post: true
      excerpt_separator: <!--more-->

repository: "https://github.com/mrshannonyoung/2020/"


# Links
# https://web.dev/native-lazy-loading/