- name: Netlify
  width: 200
  height: 53
  function: Hosted with
  description: "A web developer platform that multiplies productivity.By unifying the elements of the modern decoupled web, from local development to advanced edge logic, Netlify enables a 10x faster path to much more performant, secure, and scalable websites and apps."
  url: https://www.netlify.com/

- name: Jekyll
  width: 200
  height: 80
  function: Built with
  description: POSSE is an abbreviation for Publish (on your) Own Site, Syndicate Elsewhere.
  url: https://jekyllrb.com/